"""add phone number

Revision ID: 114116cc59c5
Revises: 35654170b0e3
Create Date: 2022-04-06 17:15:59.400425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114116cc59c5'
down_revision = '35654170b0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
